name: Automação Logs Manicure

on:
  schedule:
    - cron: '0 23 * * *' # Roda todo dia às 20h (Horário de Brasília aprox.)
  workflow_dispatch: # Permite que você rode manualmente clicando em um botão

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: pip install gspread oauth2client facebook-business pandas

      - name: Executar Automação
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          META_TOKEN: ${{ secrets.META_TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python script_manicure.py
